name: tracker_apk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  geolocator: ^11.0.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  http: ^1.2.1

 







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  workmanager: ^0.5.2

flutter:
  uses-material-design: true
