name: tracker_apk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^5.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  # path: ^1.9.0
  workmanager: ^0.5.2
  http: ^0.13.6
  permission_handler: ^11.3.0

 







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
